
create table COMPANII(ID_COMPANIE NUMBER(2) PRIMARY KEY, DENUMIRE VARCHAR2(10),LOCALITATE_SEDIU VARCHAR2(10),
	NUME_CEO VARCHAR2(20));



CREATE TABLE FILIALE(ID_COMPANIE NUMBER(2),
ID_FILIALA NUMBER(1),
DENUMIRE VARCHAR2(10),
LOCALITATE VARCHAR2(10),
NR_ANGAJATI NUMBER(4),
CONSTRAINT PK_FILIALE PRIMARY KEY (ID_COMPANIE,ID_FILIALA),
CONSTRAINT FK_FILIALE_COMPANY FOREIGN KEY (ID_COMPANIE) REFERENCES COMPANII(ID_COMPANIE));


CREATE TABLE SALARIATI( MATRICOL NUMBER(6) PRIMARY KEY,NUME VARCHAR2(10) ,
PRENUME VARCHAR2(10), 
ID_COMPANIE NUMBER(2) ,
ID_FILIALA NUMBER(1) ,
SALARIU	NUMBER(7,2),
CONSTRAINT FK_SALARIATI_FILIALE FOREIGN KEY (ID_COMPANIE,ID_FILIALA) REFERENCES FILIALE (ID_COMPANIE,ID_FILIALA));

INSERT INTO COMPANII(ID_COMPANIE,DENUMIRE,LOCALITATE_SEDIU,NUME_CEO) VALUES(1,'COMP1','BUCURESTI','CEZAR');
INSERT INTO COMPANII(ID_COMPANIE,DENUMIRE,LOCALITATE_SEDIU,NUME_CEO) VALUES(2,'COMP2','ILFOV','CEZAR');

INSERT INTO FILIALE(ID_COMPANIE,ID_FILIALA,DENUMIRE,LOCALITATE,NR_ANGAJATI) VALUES(1,1,'D1','CLUJ',10);
INSERT INTO FILIALE(ID_COMPANIE,ID_FILIALA,DENUMIRE,LOCALITATE,NR_ANGAJATI) VALUES(1,2,'C1','PLOIESTI',4);
INSERT INTO FILIALE(ID_COMPANIE,ID_FILIALA,DENUMIRE,LOCALITATE,NR_ANGAJATI) VALUES(2,1,'E1','IASI',5);


INSERT INTO SALARIATI (MATRICOL,NUME,PRENUME,ID_COMPANIE,ID_FILIALA,SALARIU) VALUES (1,'N1','P1',1,1,1000);
INSERT INTO SALARIATI (MATRICOL,NUME,PRENUME,ID_COMPANIE,ID_FILIALA,SALARIU) VALUES (2,'N2','P2',1,2,1050);
INSERT INTO SALARIATI (MATRICOL,NUME,PRENUME,ID_COMPANIE,ID_FILIALA,SALARIU) VALUES (3,'N3','P3',2,1,1500);
INSERT INTO SALARIATI (MATRICOL,NUME,PRENUME,ID_COMPANIE,ID_FILIALA,SALARIU) VALUES (4,'N4','P4',1,1,1700);



SELECT * FROM SALARIATI;
SELECT * FROM FILIALE;
SELECT * FROM COMPANII;

DESC COMPANII;
DESC FILIALE;
DESC SALARIATI;

--COMENTARIU SELECT * FROM SALARIATI WHERE SALARIU <&SALAR; ITI CERE  UNDEFINE SALAR DACA FOLOSESC &&



SELECT * FROM SALARIATI WHERE SALARIU <2000;
SELECT * FROM SALARIATI WHERE SALARIU <&&SALAR;

SELECT NUME ,PRENUME,SALARIU FROM SALARIATI WHERE SALARIU >=&SALAR;

UNDEFINE SALAR;




DROP TABLE SALARIATI;
DROP TABLE FILIALE;
DROP TABLE COMPANII;

