--DESC COMPANII;
DESC emp;
select * from emp;

select EMPNO,ENAME,SAL,DEPTNO FROM EMP WHERE SAL > 1400 ORDER BY SAL DESC,ENAME;
SELECT * FROM DEPT WHERE LOC LIKE 'CHI%'; 
-- SAU = IN LOC DE LIKE DAR FARA %
SELECT * FROM EMP
WHERE MGR =7910 ORDER BY SAL DESC;

--SELECT * FROM EMP WHERE SAL >&SALARIU;

CREATE TABLE ANGAJATI_PESTE1000 AS SELECT ENAME , EMPNO,SAL FROM EMP WHERE SAL >1500;

CREATE TABLE DEPT2 AS SELECT * FROM DEPT WHERE DEPTNO LIKE '%0';

CREATE TABLE SALGRADEOVER1000 AS SELECT * FROM SALGRADE WHERE LOSAL >1000;



SELECT * FROM ANGAJATI_PESTE1000;
SELECT * FROM DEPT2;
SELECT * FROM SALGRADEOVER1000;

DROP TABLE ANGAJATI_PESTE1000;
DROP TABLE DEPT2;
DROP TABLE SALGRADEOVER1000;



SELECT * FROM EMP WHERE HIREDATE> TO_DATE('01-03-1981','DD-MM-YYYY');
SELECT * FROM EMP WHERE to_char(hiredate,'DD-MM-YYYY'	) ='17-12-1980';


SELECT * FROM EMP  WHERE SAL>1000 AND SAL <2000;
SELECT * FROM EMP  WHERE SAL BETWEEN 1000 AND 2000;


SELECT * FROM EMP  WHERE TO_CHAR(HIREDATE ,'YYYYMMDD') BETWEEN '19810402' AND '19811202';

SELECT * FROM EMP WHERE COMM IS NULL;
SELECT * FROM EMP WHERE COMM IS NOT NULL AND COMM >0;

SELECT * FROM EMP WHERE ENAME LIKE '%LIKE%';
SELECT 'AZI ESTE DATA ' || SYSDATE || ' SI ANGAJATUL SE NUMESTE ' || ENAME FROM EMP;
SELECT 1 FROM EMP;

SELECT EMP.EMPNO , EMP.SAL , EMP.ENAME FROM EMP,DEPT WHERE EMP.DEPTNO = DEPT.DEPTNO AND DEPT.LOC='CHICAGO';
SELECT EMPNO , SAL , ENAME FROM EMP,DEPT WHERE EMP.DEPTNO = DEPT.DEPTNO AND DEPT.LOC='CHICAGO';
